spring.application.name=sportapp-user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/sportapp_user_db
spring.datasource.username=postgres
spring.datasource.password=Reamadrid9
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
